<a href="https://colab.research.google.com/github/Wipada6430205202/python_dataviz2023/blob/main/Final2023_DataViz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ลิงค์ Dashboard -> [lookerstudio](https://lookerstudio.google.com/u/1/reporting/9af44d9b-66c9-4f5c-8d89-c29d0cbbc05d/page/8PYfD?fbclid=IwAR2YVYGXKnW2yFwcWNnjlf2nb_L4U1iYmMJLgmfGTGJ7dDPJiiawcP0-kuc)

##รายชื่อสมาชิก
1. นางสาววิภาดา ห่วงสูงเนิน 643020520-2 หน้าที่รับผิดชอบ  Dash+คิดคำถาม                   
2. นายศตวรรษ มูลสันเทียะ 643021273-8  หน้าที่รับผิดชอบ  Dash+คิดคำถาม              
3. นางสาวชนม์ชนก อังคุระษี 643021263-1 หน้าที่รับผิดชอบ  Dash+คิดคำถาม                
4. นางสาวพัณณิตา ทองบ่อ 643020508-2  หน้าที่รับผิดชอบ  Code+คิดคำถาม                         
5. นางสาวศดานันท์ ทรัพย์มีมหาศาล 643021272-0 หน้าที่รับผิดชอบ Code+คิดคำถาม
6. นายจิรวัฒน์ ทวินันท์ 633020369-9  หน้าที่รับผิดชอบ Code+คิดคำถาม

## นำข้อมูลเข้า

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
import pandas as pd
import os
import numpy as np

In [ ]:
os.chdir('/content/gdrive/MyDrive/DataViz23Data/final')
!pwd #เช็ค path ที่กำลังทำงานอยู่

/content/gdrive/MyDrive/DataViz23Data/final

## รวมตารางช่วงเวลา 07/12/2017-19/12/2017  แคชเชียร์คนไหนใช้เวลาทำงานเยอะที่สุดและคนไหนใช้เวลาทำงานน้อยที่สุดและดูยอดการชำระด้วยเครดิตการ์ดและเงินสดทั้งหมด ในปี 2017
* ตอบ ปี 2017 วันที่ 7/12 - 19/12 แคชเชียร์ที่ใช้เวลาทำงานเยอะที่สุด คือ OperatorID 268
* จากตารางพบว่า cash มียอดการชำระอยู่ที่ 2​,112,171.46 us ส่วน card มียอดการชำระอยู่ที่ 2,943,462.16 us เมื่อคิดเป็นเปอร์เซ็นต์จะได้ว่า card = 58.2% cash = 41.8%

In [ ]:
df1 = pd.read_csv('/content/gdrive/MyDrive/DataViz23Data/final/POS_operator_logs_20171207-20171219.csv')
df1

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn
...,...,...,...,...,...,...
4703,8,14,171219106014514,2017-12-19T22:00:22,264,OperatorSignOff
4704,1,21,171219106021873,2017-12-19T22:02:53,124,OperatorSignOn
4705,8,15,171219106015506,2017-12-19T22:05:05,265,OperatorSignOff
4706,1,21,171219106021890,2017-12-19T22:09:47,124,OperatorSignOff
4707,1,22,171219106022935,2017-12-19T22:12:44,146,OperatorSignOff

In [ ]:
df2 = pd.read_csv('/content/gdrive/MyDrive/DataViz23Data/final/POS_transactions_20171207-20171219.csv')
df2

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34
...,...,...,...,...,...,...,...,...,...,...,...
66858,1,1712191060847,2017-12-19T11:48:35,2017-12-19T11:49:28,606,53,19,6,True,False,36.27
66859,1,1712191060848,2017-12-19T11:49:47,2017-12-19T11:50:24,606,37,15,10,True,False,43.16
66860,1,1712191060849,2017-12-19T11:50:39,2017-12-19T11:51:22,606,43,14,11,False,True,39.58
66861,1,1712191060851,2017-12-19T11:51:36,2017-12-19T11:52:28,606,52,9,9,False,True,113.96
66862,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58

In [ ]:
print(df1.isnull().any())
print(df2.isnull().any())

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool
WorkstationGroupID    False
TranID                False
BeginDateTime         False
EndDateTime           False
OperatorID            False
TranTime              False
BreakTime             False
ArtNum                False
TNcash                False
TNcard                False
Amount                False
dtype: bool

###   นำ ```POS_transactions_20171207-20171219``` เชื่อมตารางกับ```POS_operator_logs_20171207-20171219``` ด้วย ```OperatorID``` เพื่อที่จะรวมข้อมูลในช่วงเวลาเดียวกัน

In [ ]:
P2017 = df2.merge(df1, how ='left', left_on='OperatorID',right_on='OperatorID')
print(P2017.shape)
P2017

(7328682, 16)

,WorkstationGroupID_x,TranID_x,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,WorkstationGroupID_y,WorkstationID,TranID_y,BeginDateTime_y,Items
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn
1,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,22,171207106022506,2017-12-07T15:04:20,OperatorLock
2,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,22,171207106022507,2017-12-07T15:04:57,OperatorUnLock
3,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,22,171207106022509,2017-12-07T15:05:47,OperatorLock
4,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,22,171207106022510,2017-12-07T15:06:58,OperatorUnLock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7328677,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,1,8,1712191060831,2017-12-19T11:32:55,OperatorLock
7328678,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,1,8,1712191060832,2017-12-19T11:33:16,OperatorUnLock
7328679,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,1,8,1712191060845,2017-12-19T11:41:57,OperatorLock
7328680,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,1,8,1712191060846,2017-12-19T11:48:24,OperatorUnLock
7328681,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,1,8,1712191060855,2017-12-19T11:55:11,OperatorSignOff

In [ ]:
P2017nodrop = P2017.drop_duplicates(subset='TranID_x')
P2017nodrop

,WorkstationGroupID_x,TranID_x,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,WorkstationGroupID_y,WorkstationID,TranID_y,BeginDateTime_y,Items
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn
258,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn
516,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn
774,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn
1032,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7328342,1,1712191060847,2017-12-19T11:48:35,2017-12-19T11:49:28,606,53,19,6,True,False,36.27,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn
7328410,1,1712191060848,2017-12-19T11:49:47,2017-12-19T11:50:24,606,37,15,10,True,False,43.16,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn
7328478,1,1712191060849,2017-12-19T11:50:39,2017-12-19T11:51:22,606,43,14,11,False,True,39.58,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn
7328546,1,1712191060851,2017-12-19T11:51:36,2017-12-19T11:52:28,606,52,9,9,False,True,113.96,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn
7328614,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn

In [ ]:
P2017nodrop.to_csv('P2017.csv', index=False)

In [ ]:
#P2017nodrop[P2017nodrop['OperatorID']=='101'].sort_values(by=['TranTime'])

In [ ]:
P2017nodrop.groupby('OperatorID')['Amount'].sum()

OperatorID
101    178007.38
102       197.89
104    160095.98
106    134471.01
107     63372.15
108    204725.46
109    102467.82
110    182287.33
113     44803.99
114    230573.96
115    110236.76
116    154573.40
117      9080.30
118     19999.76
119    218100.10
120    156114.64
121     33158.20
123    149185.96
124    156367.93
125    174673.86
126     51192.72
127    155715.35
128    178175.73
130      9224.95
131    212729.70
132    243655.80
139     74128.02
140    200598.44
143     70129.38
145     44031.25
146    142256.73
148    107449.38
264    152488.15
265    152031.30
266    148719.26
267    146979.23
268    158011.61
269     73726.38
307      7745.88
315     20022.18
316     25545.17
333     12344.19
361     25430.56
385     57617.03
600     12726.93
605     54809.01
606     35655.41
Name: Amount, dtype: float64

In [ ]:
P2017nodrop.sum()

WorkstationGroupID_x                                               195586
TranID_x                                              8142570670015328706
BeginDateTime_x         2017-12-07T14:23:232017-12-07T14:25:092017-12-...
EndDateTime             2017-12-07T14:24:362017-12-07T14:27:002017-12-...
OperatorID                                                       11807710
TranTime                                                          4927832
BreakTime                                                         2864720
ArtNum                                                             959063
TNcash                                                              32171
TNcard                                                              34502
Amount                                                         5055633.62
WorkstationGroupID_y                                               195586
WorkstationID                                                      939803
TranID_y                                              3004904395587607826
BeginDateTime_y         2017-12-07T14:23:112017-12-07T14:23:112017-12-...
Items                   OperatorSignOnOperatorSignOnOperatorSignOnOper...
dtype: object

### เพิ่มคอลัมน์ Payment method ที่แปลงค่าจากคอลัมน์ TNcard,TNcash ที่มีค่าเป็น True,False เปลี่ยเป็นค่า card และ cash

In [ ]:
import pandas as pd

# สร้าง DataFrame
P2017 = pd.DataFrame(P2017nodrop)

# สร้างฟังก์ชันสำหรับแปลงค่า
def convert_value(TNcash):
    if TNcash ==True:
        return "cash"
    else:
        return "card"

# ใช้ .apply() เพื่อสร้างคอลัมน์ใหม่ที่แปลงค่าจาก Original_Column
P2017nodrop['Payment method'] = P2017nodrop['TNcash'].apply(convert_value)

print(P2017)

         WorkstationGroupID_x         TranID_x      BeginDateTime_x  \
0                           1  171207106022464  2017-12-07T14:23:23
258                         1  171207106022465  2017-12-07T14:25:09
516                         1  171207106022466  2017-12-07T14:27:28
774                         1  171207106022467  2017-12-07T14:28:04
1032                        1  171207106022468  2017-12-07T14:29:40
...                       ...              ...                  ...
7328342                     1    1712191060847  2017-12-19T11:48:35
7328410                     1    1712191060848  2017-12-19T11:49:47
7328478                     1    1712191060849  2017-12-19T11:50:39
7328546                     1    1712191060851  2017-12-19T11:51:36
7328614                     1    1712191060853  2017-12-19T11:52:37

                 EndDateTime  OperatorID  TranTime  BreakTime  ArtNum  TNcash  \
0        2017-12-07T14:24:36         101        73         33      23    True
258      2017-12-07T14:27:00         101       111         28      29    True
516      2017-12-07T14:27:48         101        20         16       3    True
774      2017-12-07T14:28:29         101        25         71      12    True
1032     2017-12-07T14:30:32         101        52         31       7    True
...                      ...         ...       ...        ...     ...     ...
7328342  2017-12-19T11:49:28         606        53         19       6    True
7328410  2017-12-19T11:50:24         606        37         15      10    True
7328478  2017-12-19T11:51:22         606        43         14      11   False
7328546  2017-12-19T11:52:28         606        52          9       9   False
7328614  2017-12-19T11:53:39         606        62         15      25    True

         TNcard  Amount  WorkstationGroupID_y  WorkstationID         TranID_y  \
0         False  112.71                     1             22  171207106022462
258       False   54.76                     1             22  171207106022462
516       False   14.77                     1             22  171207106022462
774       False   37.88                     1             22  171207106022462
1032      False  115.34                     1             22  171207106022462
...         ...     ...                   ...            ...              ...
7328342   False   36.27                     1              8     171207106082
7328410   False   43.16                     1              8     171207106082
7328478    True   39.58                     1              8     171207106082
7328546    True  113.96                     1              8     171207106082
7328614   False   97.58                     1              8     171207106082

             BeginDateTime_y           Items Payment method
0        2017-12-07T14:23:11  OperatorSignOn           cash
258      2017-12-07T14:23:11  OperatorSignOn           cash
516      2017-12-07T14:23:11  OperatorSignOn           cash
774      2017-12-07T14:23:11  OperatorSignOn           cash
1032     2017-12-07T14:23:11  OperatorSignOn           cash
...                      ...             ...            ...
7328342  2017-12-07T10:08:12  OperatorSignOn           cash
7328410  2017-12-07T10:08:12  OperatorSignOn           cash
7328478  2017-12-07T10:08:12  OperatorSignOn           card
7328546  2017-12-07T10:08:12  OperatorSignOn           card
7328614  2017-12-07T10:08:12  OperatorSignOn           cash

[66863 rows x 17 columns]

<ipython-input-13-c926d638ce82>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  P2017nodrop['Payment method'] = P2017nodrop['TNcash'].apply(convert_value)

In [ ]:
P2017.reset_index()

,index,WorkstationGroupID_x,TranID_x,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,WorkstationGroupID_y,WorkstationID,TranID_y,BeginDateTime_y,Items,Payment method
0,0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn,cash
1,258,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn,cash
2,516,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn,cash
3,774,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn,cash
4,1032,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn,cash
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66858,7328342,1,1712191060847,2017-12-19T11:48:35,2017-12-19T11:49:28,606,53,19,6,True,False,36.27,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn,cash
66859,7328410,1,1712191060848,2017-12-19T11:49:47,2017-12-19T11:50:24,606,37,15,10,True,False,43.16,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn,cash
66860,7328478,1,1712191060849,2017-12-19T11:50:39,2017-12-19T11:51:22,606,43,14,11,False,True,39.58,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn,card
66861,7328546,1,1712191060851,2017-12-19T11:51:36,2017-12-19T11:52:28,606,52,9,9,False,True,113.96,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn,card
66862,7328614,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn,cash

In [ ]:
#P2017_.drop(['mp_app_rank','mp_app_vote_percent'], axis=1,inplace=True)
#P2017

NameError: ignored

In [ ]:
P2017.to_csv('P2017new.csv', index=False)

## รวมตารางช่วงเวลา 13/02/2019-26/02/2019 เพื่อนำไปเปรียบเทียบรายรับของ 2 ช่วงเวลาใน 1 ปี
* ตอบ ในปี 2019 ในช่วงแรกมียอดขายมากกว่า ช่วงหลัง เกือบเท่าตัวเนื่องจากมีช่วงเวลาเฉลี่ยที่เครื่องแคชเชียร์ว่างน้อยกว่าช่วงหลังเกือบเท่าตัวเช่นกัน

In [ ]:
df3 = pd.read_csv('/content/gdrive/MyDrive/DataViz23Data/final/POS_operator_logs_20190213-20190226.csv')
df3

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,19,1902131060192,2019-02-13T05:37:55,269,OperatorSignOn
1,8,18,1902131060182,2019-02-13T05:37:55,268,OperatorSignOn
2,8,17,1902131060172,2019-02-13T05:38:43,267,OperatorSignOn
3,1,4,190213106042,2019-02-13T07:01:26,332,OperatorSignOn
4,1,7,190213106072,2019-02-13T07:01:57,10,OperatorSignOn
...,...,...,...,...,...,...
5213,1,12,190226106012628,2019-02-26T21:44:52,332,OperatorUnLock
5214,1,20,190226106020667,2019-02-26T21:53:12,131,OperatorSignOff
5215,1,12,190226106012644,2019-02-26T22:00:49,332,OperatorLock
5216,1,12,190226106012645,2019-02-26T22:01:48,332,OperatorUnLock
5217,1,12,190226106012648,2019-02-26T22:03:46,332,OperatorSignOff

In [ ]:
df4 = pd.read_csv('/content/gdrive/MyDrive/DataViz23Data/final/POS_transactions_20190213-20190226.csv')
df4

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79
1,1,190213106054,2019-02-13T07:50:14,2019-02-13T07:50:23,101,9,17,3,True,False,13.19
2,1,190213106055,2019-02-13T07:50:40,2019-02-13T07:51:01,101,21,209,6,True,False,21.20
3,1,190213106058,2019-02-13T07:54:30,2019-02-13T07:55:05,101,35,16,1,True,False,106.20
4,1,190213106059,2019-02-13T07:55:21,2019-02-13T07:55:27,101,6,17,1,True,False,106.20
...,...,...,...,...,...,...,...,...,...,...,...
47061,1,19022310606490,2019-02-23T19:39:47,2019-02-23T19:40:21,606,34,38,8,False,True,26.45
47062,1,19022310606494,2019-02-23T19:40:59,2019-02-23T19:41:18,606,19,11,3,False,True,14.97
47063,1,19022310606496,2019-02-23T19:41:29,2019-02-23T19:41:56,606,27,36,6,False,True,55.34
47064,1,19022310606499,2019-02-23T19:42:32,2019-02-23T19:42:57,606,25,22,11,True,False,47.42
47065,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38

In [ ]:
print(df3.isnull().any())
print(df4.isnull().any())

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool
WorkstationGroupID    False
TranID                False
BeginDateTime         False
EndDateTime           False
OperatorID            False
TranTime              False
BreakTime             False
ArtNum                False
TNcash                False
TNcard                False
Amount                False
dtype: bool

###   นำ ```POS_operator_logs_20190213-20190226``` เชื่อมตารางกับ```POS_transactions_20190213-20190226``` ด้วย ```OperatorID``` เพื่อที่จะรวมข้อมูลในช่วงเวลาเดียวกัน

In [ ]:
P2019F = df4.merge(df3, how ='left', left_on='OperatorID',right_on='OperatorID')
print(P2019F.shape)
P2019F

(8638572, 16)

,WorkstationGroupID_x,TranID_x,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,WorkstationGroupID_y,WorkstationID,TranID_y,BeginDateTime_y,Items
0,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,1,7,190213106072,2019-02-13T07:01:57,OperatorSignOn
1,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,1,7,190213106074,2019-02-13T07:02:16,OperatorSignOff
2,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,1,8,190213106082,2019-02-13T10:32:12,OperatorSignOn
3,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,1,8,190213106084,2019-02-13T10:32:15,OperatorSignOff
4,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,1,7,1902131060717,2019-02-13T10:32:43,OperatorSignOn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8638567,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,1,6,19022310606409,2019-02-23T17:32:11,OperatorSignOff
8638568,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,1,6,19022310606411,2019-02-23T18:35:29,OperatorSignOn
8638569,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,1,6,19022310606481,2019-02-23T19:29:15,OperatorSignOff
8638570,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,1,6,19022310606483,2019-02-23T19:36:38,OperatorSignOn
8638571,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,1,6,19022310606502,2019-02-23T19:46:27,OperatorSignOff

In [ ]:
P2019Fnodrop = P2019F.drop_duplicates(subset='TranID_x')
P2019Fnodrop

,WorkstationGroupID_x,TranID_x,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,WorkstationGroupID_y,WorkstationID,TranID_y,BeginDateTime_y,Items
0,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,1,7,190213106072,2019-02-13T07:01:57,OperatorSignOn
518,1,190213106054,2019-02-13T07:50:14,2019-02-13T07:50:23,101,9,17,3,True,False,13.19,1,5,190213106052,2019-02-13T07:49:57,OperatorSignOn
910,1,190213106055,2019-02-13T07:50:40,2019-02-13T07:51:01,101,21,209,6,True,False,21.20,1,5,190213106052,2019-02-13T07:49:57,OperatorSignOn
1302,1,190213106058,2019-02-13T07:54:30,2019-02-13T07:55:05,101,35,16,1,True,False,106.20,1,5,190213106052,2019-02-13T07:49:57,OperatorSignOn
1694,1,190213106059,2019-02-13T07:55:21,2019-02-13T07:55:27,101,6,17,1,True,False,106.20,1,5,190213106052,2019-02-13T07:49:57,OperatorSignOn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8638282,1,19022310606490,2019-02-23T19:39:47,2019-02-23T19:40:21,606,34,38,8,False,True,26.45,1,6,19021410606149,2019-02-14T10:42:43,OperatorSignOn
8638340,1,19022310606494,2019-02-23T19:40:59,2019-02-23T19:41:18,606,19,11,3,False,True,14.97,1,6,19021410606149,2019-02-14T10:42:43,OperatorSignOn
8638398,1,19022310606496,2019-02-23T19:41:29,2019-02-23T19:41:56,606,27,36,6,False,True,55.34,1,6,19021410606149,2019-02-14T10:42:43,OperatorSignOn
8638456,1,19022310606499,2019-02-23T19:42:32,2019-02-23T19:42:57,606,25,22,11,True,False,47.42,1,6,19021410606149,2019-02-14T10:42:43,OperatorSignOn
8638514,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,1,6,19021410606149,2019-02-14T10:42:43,OperatorSignOn

In [ ]:
P2019Fnodrop.groupby('OperatorID')['Amount'].sum()

OperatorID
10          1.79
101    178432.67
102     13595.93
104    126837.26
105     20992.47
106    107152.99
108    117598.92
111    126953.70
112     95789.79
113     64575.78
114     90290.38
117      4006.07
119    154342.97
120     50462.35
121      6577.99
125    188435.72
131    173617.21
133     54172.08
139      4559.01
143     27769.80
145     42966.26
267    135433.08
268    142832.34
269    150261.31
301      1092.03
303    107531.47
315      7663.94
316      2437.34
323    106954.43
328    129566.34
330      6958.55
332    140480.68
334      4490.57
338    207902.68
342    230382.99
346     82780.21
365     20007.68
381       553.07
385     11071.26
600     18446.32
601     10241.26
603     14589.46
606     37959.74
Name: Amount, dtype: float64

### เพิ่มคอลัมน์ Payment method ที่แปลงค่าจากคอลัมน์ TNcard,TNcash ที่มีค่าเป็น True,False เปลี่ยเป็นค่า card และ cash

In [ ]:
P2019F = pd.DataFrame(P2019Fnodrop)

def combine_values(column):
    if column['TNcash'] == True and column['TNcard'] == False:
        return 'cash'
    elif column['TNcash'] == False and column['TNcard'] == True:
        return 'card'
    elif column['TNcash'] == False and column['TNcard'] == False:
        return 'missing'
    elif column['TNcash'] == True and column['TNcard'] == True:
        return 'missing'
    else:
        return 'unknown'

# ใช้ .apply() เพื่อสร้างคอลัมน์ใหม่
P2019Fnodrop['Payment method'] = P2019F.apply(combine_values, axis=1)
print(P2019F)

         WorkstationGroupID_x        TranID_x      BeginDateTime_x  \
0                           1  19022310606223  2019-02-23T14:35:12
518                         1    190213106054  2019-02-13T07:50:14
910                         1    190213106055  2019-02-13T07:50:40
1302                        1    190213106058  2019-02-13T07:54:30
1694                        1    190213106059  2019-02-13T07:55:21
...                       ...             ...                  ...
8638282                     1  19022310606490  2019-02-23T19:39:47
8638340                     1  19022310606494  2019-02-23T19:40:59
8638398                     1  19022310606496  2019-02-23T19:41:29
8638456                     1  19022310606499  2019-02-23T19:42:32
8638514                     1  19022310606500  2019-02-23T19:43:19

                 EndDateTime  OperatorID  TranTime  BreakTime  ArtNum  TNcash  \
0        2019-02-23T14:35:12          10         0          2       1   False
518      2019-02-13T07:50:23         101         9         17       3    True
910      2019-02-13T07:51:01         101        21        209       6    True
1302     2019-02-13T07:55:05         101        35         16       1    True
1694     2019-02-13T07:55:27         101         6         17       1    True
...                      ...         ...       ...        ...     ...     ...
8638282  2019-02-23T19:40:21         606        34         38       8   False
8638340  2019-02-23T19:41:18         606        19         11       3   False
8638398  2019-02-23T19:41:56         606        27         36       6   False
8638456  2019-02-23T19:42:57         606        25         22      11    True
8638514  2019-02-23T19:44:20         606        61         18      13    True

         TNcard  Amount  WorkstationGroupID_y  WorkstationID        TranID_y  \
0         False    1.79                     1              7    190213106072
518       False   13.19                     1              5    190213106052
910       False   21.20                     1              5    190213106052
1302      False  106.20                     1              5    190213106052
1694      False  106.20                     1              5    190213106052
...         ...     ...                   ...            ...             ...
8638282    True   26.45                     1              6  19021410606149
8638340    True   14.97                     1              6  19021410606149
8638398    True   55.34                     1              6  19021410606149
8638456   False   47.42                     1              6  19021410606149
8638514   False  129.38                     1              6  19021410606149

             BeginDateTime_y           Items Payment method
0        2019-02-13T07:01:57  OperatorSignOn        missing
518      2019-02-13T07:49:57  OperatorSignOn           cash
910      2019-02-13T07:49:57  OperatorSignOn           cash
1302     2019-02-13T07:49:57  OperatorSignOn           cash
1694     2019-02-13T07:49:57  OperatorSignOn           cash
...                      ...             ...            ...
8638282  2019-02-14T10:42:43  OperatorSignOn           card
8638340  2019-02-14T10:42:43  OperatorSignOn           card
8638398  2019-02-14T10:42:43  OperatorSignOn           card
8638456  2019-02-14T10:42:43  OperatorSignOn           cash
8638514  2019-02-14T10:42:43  OperatorSignOn           cash

[46915 rows x 17 columns]

<ipython-input-22-c232dde7e4e1>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  P2019Fnodrop['Payment method'] = P2019F.apply(combine_values, axis=1)

In [ ]:
P2019F.reset_index()

,index,WorkstationGroupID_x,TranID_x,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,WorkstationGroupID_y,WorkstationID,TranID_y,BeginDateTime_y,Items,Payment method
0,0,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,1,7,190213106072,2019-02-13T07:01:57,OperatorSignOn,missing
1,518,1,190213106054,2019-02-13T07:50:14,2019-02-13T07:50:23,101,9,17,3,True,False,13.19,1,5,190213106052,2019-02-13T07:49:57,OperatorSignOn,cash
2,910,1,190213106055,2019-02-13T07:50:40,2019-02-13T07:51:01,101,21,209,6,True,False,21.20,1,5,190213106052,2019-02-13T07:49:57,OperatorSignOn,cash
3,1302,1,190213106058,2019-02-13T07:54:30,2019-02-13T07:55:05,101,35,16,1,True,False,106.20,1,5,190213106052,2019-02-13T07:49:57,OperatorSignOn,cash
4,1694,1,190213106059,2019-02-13T07:55:21,2019-02-13T07:55:27,101,6,17,1,True,False,106.20,1,5,190213106052,2019-02-13T07:49:57,OperatorSignOn,cash
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46910,8638282,1,19022310606490,2019-02-23T19:39:47,2019-02-23T19:40:21,606,34,38,8,False,True,26.45,1,6,19021410606149,2019-02-14T10:42:43,OperatorSignOn,card
46911,8638340,1,19022310606494,2019-02-23T19:40:59,2019-02-23T19:41:18,606,19,11,3,False,True,14.97,1,6,19021410606149,2019-02-14T10:42:43,OperatorSignOn,card
46912,8638398,1,19022310606496,2019-02-23T19:41:29,2019-02-23T19:41:56,606,27,36,6,False,True,55.34,1,6,19021410606149,2019-02-14T10:42:43,OperatorSignOn,card
46913,8638456,1,19022310606499,2019-02-23T19:42:32,2019-02-23T19:42:57,606,25,22,11,True,False,47.42,1,6,19021410606149,2019-02-14T10:42:43,OperatorSignOn,cash
46914,8638514,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,1,6,19021410606149,2019-02-14T10:42:43,OperatorSignOn,cash

In [ ]:
P2019Fnodrop.drop(['BeginDateTime_x','EndDateTime','TranTime','BreakTime', 'BeginDateTime_y','WorkstationGroupID_y'], axis=1,inplace=True)
P2019Fnodrop

<ipython-input-24-d9d98480bc54>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  P2019Fnodrop.drop(['BeginDateTime_x','EndDateTime','TranTime','BreakTime', 'BeginDateTime_y','WorkstationGroupID_y'], axis=1,inplace=True)

,WorkstationGroupID_x,TranID_x,OperatorID,ArtNum,TNcash,TNcard,Amount,WorkstationID,TranID_y,Items,Payment method
0,1,19022310606223,10,1,False,False,1.79,7,190213106072,OperatorSignOn,missing
518,1,190213106054,101,3,True,False,13.19,5,190213106052,OperatorSignOn,cash
910,1,190213106055,101,6,True,False,21.20,5,190213106052,OperatorSignOn,cash
1302,1,190213106058,101,1,True,False,106.20,5,190213106052,OperatorSignOn,cash
1694,1,190213106059,101,1,True,False,106.20,5,190213106052,OperatorSignOn,cash
...,...,...,...,...,...,...,...,...,...,...,...
8638282,1,19022310606490,606,8,False,True,26.45,6,19021410606149,OperatorSignOn,card
8638340,1,19022310606494,606,3,False,True,14.97,6,19021410606149,OperatorSignOn,card
8638398,1,19022310606496,606,6,False,True,55.34,6,19021410606149,OperatorSignOn,card
8638456,1,19022310606499,606,11,True,False,47.42,6,19021410606149,OperatorSignOn,cash
8638514,1,19022310606500,606,13,True,False,129.38,6,19021410606149,OperatorSignOn,cash

In [ ]:
P2019F.to_csv('P2019F.csv', index=False)

## รวมตารางช่วงเวลา 28/03/2019-10/04/2019 เพื่อนำไปเปรียบเทียบรายรับของ 2 ช่วงเวลาใน 1 ปี

In [ ]:
df5 = pd.read_csv('/content/gdrive/MyDrive/DataViz23Data/final/POS_operator_logs_20190328-20190410.csv')
df5

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,19,1903281060192,2019-03-28T06:08:13,269,OperatorSignOn
1,8,18,1903281060182,2019-03-28T06:09:13,268,OperatorSignOn
2,8,17,1903281060172,2019-03-28T06:08:33,267,OperatorSignOn
3,1,4,190328106042,2019-03-28T07:04:45,104,OperatorSignOn
4,1,6,190328106062,2019-03-28T07:18:38,125,OperatorSignOn
...,...,...,...,...,...,...
4173,1,3,19041010603798,2019-04-10T21:53:58,104,OperatorSignOff
4174,1,4,190410106041042,2019-04-10T21:54:30,304,OperatorSignOff
4175,1,4,190410106041044,2019-04-10T21:55:05,104,OperatorSignOn
4176,1,5,19041010605515,2019-04-10T22:00:25,136,OperatorSignOff
4177,1,4,190410106041061,2019-04-10T22:10:57,104,OperatorSignOff

In [ ]:
df6 = pd.read_csv('/content/gdrive/MyDrive/DataViz23Data/final/POS_transactions_20190328-20190410.csv')
df6

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,1.904031e+13,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99
1,1,1.903291e+13,2019-03-29T14:04:50,2019-03-29T14:05:31,101,41,21,6,True,False,13.74
2,1,1.903291e+13,2019-03-29T14:05:52,2019-03-29T14:06:35,101,43,44,12,True,False,97.47
3,1,1.903291e+13,2019-03-29T14:07:19,2019-03-29T14:07:43,101,24,25,6,False,True,37.18
4,1,1.903291e+13,2019-03-29T14:08:08,2019-03-29T14:09:44,101,96,18,48,True,False,154.70
...,...,...,...,...,...,...,...,...,...,...,...
49335,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14
49336,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90
49337,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99
49338,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88
49339,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33

In [ ]:
print(df5.isnull().any())
print(df6.isnull().any())

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool
WorkstationGroupID    False
TranID                False
BeginDateTime         False
EndDateTime           False
OperatorID            False
TranTime              False
BreakTime             False
ArtNum                False
TNcash                False
TNcard                False
Amount                False
dtype: bool

###   นำ ```POS_operator_logs_20190328-20190410``` เชื่อมตารางกับ```POS_transactions_20190328-20190410``` ด้วย ```OperatorID``` เพื่อที่จะรวมข้อมูลในช่วงเวลาเดียวกัน

In [ ]:
P2019Mnodup = df6.merge(df5, how ='left', left_on='OperatorID',right_on='OperatorID')
print(P2019Mnodup.shape)
P2019Mnodup

(5905674, 16)

,WorkstationGroupID_x,TranID_x,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,WorkstationGroupID_y,WorkstationID,TranID_y,BeginDateTime_y,Items
0,1,1.904031e+13,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99,1,20,1903281060202,2019-03-28T08:05:15,OperatorSignOn
1,1,1.904031e+13,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99,1,20,1903281060204,2019-03-28T08:05:15,OperatorSignOff
2,1,1.904031e+13,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99,1,1,190328106012,2019-03-28T10:37:43,OperatorSignOn
3,1,1.904031e+13,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99,1,1,190328106014,2019-03-28T10:38:16,OperatorSignOff
4,1,1.904031e+13,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99,1,13,19032810601327,2019-03-28T11:02:21,OperatorSignOn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5905669,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,1,22,190410106022111,2019-04-10T12:03:11,OperatorSignOff
5905670,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,1,22,190410106022113,2019-04-10T13:39:49,OperatorSignOn
5905671,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,1,22,190410106022128,2019-04-10T13:51:42,OperatorLock
5905672,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,1,22,190410106022129,2019-04-10T13:52:27,OperatorUnLock
5905673,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,1,22,190410106022148,2019-04-10T14:12:35,OperatorSignOff

In [ ]:
P2019Mnodup = P2019Mnodup.drop_duplicates(subset='TranID_x')
P2019Mnodup

,WorkstationGroupID_x,TranID_x,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,WorkstationGroupID_y,WorkstationID,TranID_y,BeginDateTime_y,Items
0,1,1.904031e+13,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99,1,20,1903281060202,2019-03-28T08:05:15,OperatorSignOn
500,1,1.903291e+13,2019-03-29T14:04:50,2019-03-29T14:05:31,101,41,21,6,True,False,13.74,1,7,19032910607383,2019-03-29T14:04:39,OperatorSignOn
700,1,1.903291e+13,2019-03-29T14:05:52,2019-03-29T14:06:35,101,43,44,12,True,False,97.47,1,7,19032910607383,2019-03-29T14:04:39,OperatorSignOn
900,1,1.903291e+13,2019-03-29T14:07:19,2019-03-29T14:07:43,101,24,25,6,False,True,37.18,1,7,19032910607383,2019-03-29T14:04:39,OperatorSignOn
1100,1,1.903291e+13,2019-03-29T14:08:08,2019-03-29T14:09:44,101,96,18,48,True,False,154.70,1,7,19032910607383,2019-03-29T14:04:39,OperatorSignOn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5853918,1,1.904021e+11,2019-04-02T11:08:22,2019-04-02T11:09:14,603,52,16,8,True,False,24.93,1,13,1903281060132,2019-03-28T09:55:03,OperatorSignOn
5853966,1,1.904021e+11,2019-04-02T11:09:30,2019-04-02T11:10:04,603,34,17,17,True,False,51.71,1,13,1903281060132,2019-03-28T09:55:03,OperatorSignOn
5854014,1,1.904021e+11,2019-04-02T11:10:21,2019-04-02T11:11:03,603,42,10,19,True,False,41.95,1,13,1903281060132,2019-03-28T09:55:03,OperatorSignOn
5854062,1,1.904021e+11,2019-04-02T11:11:13,2019-04-02T11:11:42,603,29,12,9,False,True,47.96,1,13,1903281060132,2019-03-28T09:55:03,OperatorSignOn
5854110,1,1.904021e+11,2019-04-02T11:11:54,2019-04-02T11:12:16,603,22,7,6,True,False,17.45,1,13,1903281060132,2019-03-28T09:55:03,OperatorSignOn

In [ ]:
P2019Mnodup.groupby('OperatorID')['Amount'].sum()

OperatorID
10         11.99
101    174099.98
102     38336.92
104    196483.01
105     31894.55
106     71691.55
108    182004.77
111     40186.64
112    141924.58
113     65670.80
114    105096.87
115       434.37
116       478.45
117      1030.59
118       674.26
119      1576.27
121        75.45
125      1055.17
128       751.97
131       679.65
133      3801.18
139       442.21
267       188.01
301       549.34
303       665.93
304        21.02
311        64.58
315       584.86
316       204.99
317       181.17
323      1110.91
346       542.22
361        96.68
385       389.06
600        85.82
603       184.00
Name: Amount, dtype: float64

### เพิ่มคอลัมน์ Payment method ที่แปลงค่าจากคอลัมน์ TNcard,TNcash ที่มีค่าเป็น True,False เปลี่ยเป็นค่า card และ cash

In [ ]:
P2019M = pd.DataFrame(P2019Mnodup)

def combine_values(column):
    if column['TNcash'] == True and column['TNcard'] == False:
        return 'cash'
    elif column['TNcash'] == False and column['TNcard'] == True:
        return 'card'
    elif column['TNcash'] == False and column['TNcard'] == False:
        return 'missing'
    elif column['TNcash'] == True and column['TNcard'] == True:
        return 'missing'
    else:
        return 'unknown'

# ใช้ .apply() เพื่อสร้างคอลัมน์ใหม่
P2019Mnodup['Payment method'] = P2019M.apply(combine_values, axis=1)
print(P2019M)

         WorkstationGroupID_x      TranID_x      BeginDateTime_x  \
0                           1  1.904031e+13  2019-04-03T13:28:17
500                         1  1.903291e+13  2019-03-29T14:04:50
700                         1  1.903291e+13  2019-03-29T14:05:52
900                         1  1.903291e+13  2019-03-29T14:07:19
1100                        1  1.903291e+13  2019-03-29T14:08:08
...                       ...           ...                  ...
5853918                     1  1.904021e+11  2019-04-02T11:08:22
5853966                     1  1.904021e+11  2019-04-02T11:09:30
5854014                     1  1.904021e+11  2019-04-02T11:10:21
5854062                     1  1.904021e+11  2019-04-02T11:11:13
5854110                     1  1.904021e+11  2019-04-02T11:11:54

                 EndDateTime  OperatorID  TranTime  BreakTime  ArtNum  TNcash  \
0        2019-04-03T13:28:17          10         0          1       1   False
500      2019-03-29T14:05:31         101        41         21       6    True
700      2019-03-29T14:06:35         101        43         44      12    True
900      2019-03-29T14:07:43         101        24         25       6   False
1100     2019-03-29T14:09:44         101        96         18      48    True
...                      ...         ...       ...        ...     ...     ...
5853918  2019-04-02T11:09:14         603        52         16       8    True
5853966  2019-04-02T11:10:04         603        34         17      17    True
5854014  2019-04-02T11:11:03         603        42         10      19    True
5854062  2019-04-02T11:11:42         603        29         12       9   False
5854110  2019-04-02T11:12:16         603        22          7       6    True

         TNcard  Amount  WorkstationGroupID_y  WorkstationID        TranID_y  \
0         False   11.99                     1             20   1903281060202
500       False   13.74                     1              7  19032910607383
700       False   97.47                     1              7  19032910607383
900        True   37.18                     1              7  19032910607383
1100      False  154.70                     1              7  19032910607383
...         ...     ...                   ...            ...             ...
5853918   False   24.93                     1             13   1903281060132
5853966   False   51.71                     1             13   1903281060132
5854014   False   41.95                     1             13   1903281060132
5854062    True   47.96                     1             13   1903281060132
5854110   False   17.45                     1             13   1903281060132

             BeginDateTime_y           Items Payment method
0        2019-03-28T08:05:15  OperatorSignOn        missing
500      2019-03-29T14:04:39  OperatorSignOn           cash
700      2019-03-29T14:04:39  OperatorSignOn           cash
900      2019-03-29T14:04:39  OperatorSignOn           card
1100     2019-03-29T14:04:39  OperatorSignOn           cash
...                      ...             ...            ...
5853918  2019-03-28T09:55:03  OperatorSignOn           cash
5853966  2019-03-28T09:55:03  OperatorSignOn           cash
5854014  2019-03-28T09:55:03  OperatorSignOn           cash
5854062  2019-03-28T09:55:03  OperatorSignOn           card
5854110  2019-03-28T09:55:03  OperatorSignOn           cash

[13181 rows x 17 columns]

<ipython-input-32-96cf8bdd0aea>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  P2019Mnodup['Payment method'] = P2019M.apply(combine_values, axis=1)

In [ ]:
P2019M.reset_index()

,index,WorkstationGroupID_x,TranID_x,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,WorkstationGroupID_y,WorkstationID,TranID_y,BeginDateTime_y,Items,Payment method
0,0,1,1.904031e+13,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99,1,20,1903281060202,2019-03-28T08:05:15,OperatorSignOn,missing
1,500,1,1.903291e+13,2019-03-29T14:04:50,2019-03-29T14:05:31,101,41,21,6,True,False,13.74,1,7,19032910607383,2019-03-29T14:04:39,OperatorSignOn,cash
2,700,1,1.903291e+13,2019-03-29T14:05:52,2019-03-29T14:06:35,101,43,44,12,True,False,97.47,1,7,19032910607383,2019-03-29T14:04:39,OperatorSignOn,cash
3,900,1,1.903291e+13,2019-03-29T14:07:19,2019-03-29T14:07:43,101,24,25,6,False,True,37.18,1,7,19032910607383,2019-03-29T14:04:39,OperatorSignOn,card
4,1100,1,1.903291e+13,2019-03-29T14:08:08,2019-03-29T14:09:44,101,96,18,48,True,False,154.70,1,7,19032910607383,2019-03-29T14:04:39,OperatorSignOn,cash
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13176,5853918,1,1.904021e+11,2019-04-02T11:08:22,2019-04-02T11:09:14,603,52,16,8,True,False,24.93,1,13,1903281060132,2019-03-28T09:55:03,OperatorSignOn,cash
13177,5853966,1,1.904021e+11,2019-04-02T11:09:30,2019-04-02T11:10:04,603,34,17,17,True,False,51.71,1,13,1903281060132,2019-03-28T09:55:03,OperatorSignOn,cash
13178,5854014,1,1.904021e+11,2019-04-02T11:10:21,2019-04-02T11:11:03,603,42,10,19,True,False,41.95,1,13,1903281060132,2019-03-28T09:55:03,OperatorSignOn,cash
13179,5854062,1,1.904021e+11,2019-04-02T11:11:13,2019-04-02T11:11:42,603,29,12,9,False,True,47.96,1,13,1903281060132,2019-03-28T09:55:03,OperatorSignOn,card
13180,5854110,1,1.904021e+11,2019-04-02T11:11:54,2019-04-02T11:12:16,603,22,7,6,True,False,17.45,1,13,1903281060132,2019-03-28T09:55:03,OperatorSignOn,cash

In [ ]:
P2019Mnodup.drop(['BeginDateTime_x','EndDateTime','TranTime','BreakTime', 'BeginDateTime_y','WorkstationGroupID_y'], axis=1,inplace=True)
P2019Mnodup

<ipython-input-34-256c9792b4c4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  P2019Mnodup.drop(['BeginDateTime_x','EndDateTime','TranTime','BreakTime', 'BeginDateTime_y','WorkstationGroupID_y'], axis=1,inplace=True)

,WorkstationGroupID_x,TranID_x,OperatorID,ArtNum,TNcash,TNcard,Amount,WorkstationID,TranID_y,Items,Payment method
0,1,1.904031e+13,10,1,False,False,11.99,20,1903281060202,OperatorSignOn,missing
500,1,1.903291e+13,101,6,True,False,13.74,7,19032910607383,OperatorSignOn,cash
700,1,1.903291e+13,101,12,True,False,97.47,7,19032910607383,OperatorSignOn,cash
900,1,1.903291e+13,101,6,False,True,37.18,7,19032910607383,OperatorSignOn,card
1100,1,1.903291e+13,101,48,True,False,154.70,7,19032910607383,OperatorSignOn,cash
...,...,...,...,...,...,...,...,...,...,...,...
5853918,1,1.904021e+11,603,8,True,False,24.93,13,1903281060132,OperatorSignOn,cash
5853966,1,1.904021e+11,603,17,True,False,51.71,13,1903281060132,OperatorSignOn,cash
5854014,1,1.904021e+11,603,19,True,False,41.95,13,1903281060132,OperatorSignOn,cash
5854062,1,1.904021e+11,603,9,False,True,47.96,13,1903281060132,OperatorSignOn,card
5854110,1,1.904021e+11,603,6,True,False,17.45,13,1903281060132,OperatorSignOn,cash

In [ ]:
P2019M.to_csv('P2019M.csv', index=False)

In [ ]:
#new_column_names = { 'mp_app_rank': 'mp_app_rank1','mp_app_vote': 'mp_app_vote1','name': 'name1'}

In [ ]:
#df_MPR1 = df_MPR1.rename(columns=new_column_names)
#df_MPR1

## รวมตารางปี 2019

In [ ]:
#P2019 = P2019Fnodrop.merge(P2019Mnodup, how ='left', left_on='OperatorID',right_on='OperatorID',left_index=False, right_index=False)
#print(P2019.shape)
#P2019